"""Add Task and TaskImage

Revision ID: a042ad29c965
Revises: 
Create Date: 2024-08-18 14:59:00.217133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a042ad29c965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA tasks")

    op.create_table('task',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    schema='tasks'
    )
    op.create_table('task_image',
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['tasks.task.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_image_task'), 'task_image', ['task'], unique=False, schema='tasks')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_index(op.f('ix_tasks_task_image_task'), table_name='task_image', schema='tasks')
    op.drop_table('task_image', schema='tasks')
    op.drop_table('task', schema='tasks')
    op.execute("DROP SCHEMA tasks")
    # ### end Alembic commands ###
